const fs = require('fs');

let file = '// This file is generated by buildLogos.js\n';
file += 'let logos = {\n';

fs.readdirSync('./logos')
  .filter(filename => {
    return filename.match(/\.png$/);
  })
  .forEach(filename => {
    let match = filename.match(/(.+)\.png$/);
    if (match === null) {
      return;
    }
    let logoName = match[1];

    // Unlike in the images task, we only support png
    let image = fs.readFileSync(`./logos/${filename}`);
    let b64 = new Buffer(image).toString('base64');
    file += `  '${logoName}': 'data:image/png;base64, ${b64}',\n`
  })

file += '};\nmodule.exports = logos;\n';
fs.writeFileSync('./logos.js', file);
